### PR TITLE
Navigation Edit

### PR DESCRIPTION
**Pull request by bsavardmsk**
This changes give the user the option to add to the configuration file top-level-menu: True to make the menu in it's own menu

Preview of the configuration.py in the netbox configuration directory
```
        'netbox_plugin_mclag': {
        'top_level_menu': True,
        }
```

image

### CODE REVIEW

**Comment by bsavardmsk** [comment]
Adding the Install Steps in the Readme

**Comment by pv2b** [comment]
Thank you for your contribution for the install documentation!

I improved it slightly, changing some grammar and adding a missed step. I also  added uninstallation instructions, as well as documentation for the new configuration option for top-level menus that you added. (Thanks for that too!)

**Comment by pv2b** [comment]
Some feedback for the future: It would have been better if you made this as two separate branches and pull requests. Adding the feature for top-level menus and adding installation instructions are two separate features, and it would have been easier to handle them separately.

**Comment by bsavardmsk** [comment]
Perfect will do next time, I’m quite new at PRs and github haha !

Thanks for the feedback !

Cheers !
Ben

De : Per von Zweigbergk ***@***.***>
Envoyé : February 3, 2024 4:53 AM
À : pv2b/netbox-plugin-mclag ***@***.***>
Cc : Benjamin Savard ***@***.***>; Author ***@***.***>
Objet : Re: [pv2b/netbox-plugin-mclag] Navigation Edit (PR #2)


Some feedback for the future: It would have been better if you made this as two separate branches and pull requests. Adding the feature for top-level menus and adding installation instructions are two separate features, and it would have been easier to handle them separately.

**Pull request merged**
